services:
   dnsmasq:
      build: dnsmasq/.
      image: docker.io/ronaldvk90/dnsmasq
      network_mode: "host"
      cap_add:
      - NET_ADMIN
      - NET_RAW
      restart: always
      env_file: .env
   tftp:
      build: tftp/.
      image: docker.io/ronaldvk90/tftp
      network_mode: "host"
      restart: always
      env_file: .env
   webserver:
      build: ./webserver/
      ports:
      - 80:80
      volumes:
      - ./webserver/www:/var/www/html/
      networks:
      - internal
      restart: always
      env_file: .env
   php: 
      image: docker.io/php:fpm-alpine
      volumes:
      - ./webserver/www:/var/www/html/
      networks:
      - internal
      restart: always
      env_file: .env
networks:
   internal:
      driver: bridge
